### ISSUE TITLE
Support for border in `ignore`

### ISSUE THREAD

**Issue by lutien** [dcrtantuco/stylelint-8-point-grid#16]
Is there any specific reason why `border` property can not be ignored? 
If it is possible in theory I could make a PR to support that 🙂

**Comment by lutien** [comment]
Create a PR already 🙂

**Comment by dcrtantuco** [comment]
Sorry for the late response.

Honestly, I'm not sure how to go about this at first so I search and found this article:
https://builttoadapt.io/8-point-grid-borders-and-layouts-e91eb97f5091?gi=d9953d055d8d
It's a great article and it explain well how to go about border on 8-point grid

I leaning towards using the second approach (as said in the article):
`allowing the 1px border to hold space outside of the 8px internal padding`
So I think there's no need to apply 8 point grid on borders.

Also, by using `box-sizing: border-box`, it will include border and padding on final width and height of the element.

**Comment by dcrtantuco** [comment]
Also, I think it's uncommon to use large values for border-width 
Usually, it's 1px 2px, 4px etc

**Comment by lutien** [comment]
@dcrtantuco, I think I probably understood something wrong then 🙂  Do you mean that at the moment border width will not be affected by the plugin?

**Comment by dcrtantuco** [comment]
yes! it doesn't include border width at the moment.

**Comment by lutien** [comment]
@dcrtantuco, cool! thank you for the response! Then I'll close my PR 🙂

**Comment by dcrtantuco** [comment]
welcome!
